#!/bin/zsh

alias ls="colorls --sd"
alias la='colorls -lAh --sd'
alias code='codium'
alias e='code'
alias c='code'
alias subl=' /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl .'
alias o='open'
alias ..='cd ..'
alias py='python'
alias activate='source ./bin/activate'
alias grep='grep --color'

alias dc='docker compose -d'
alias dcu='docker compose up -d --build'

alias lorem='echo "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet." | pbcopy'

alias gits='git status'
alias gitl='git log --graph'
alias gita='git add'
alias gitc='git commit -m'
alias gitca='git commit --amend --no-edit'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gitp='git pull'
alias gitf='git fetch'
alias gitd='git diff'

alias src='source ~/.zshrc'

function pwdcp
{
    echo -n `pwd`/$1 | pbcopy
}
